data_config:
  path: ./data/input.txt
  block_size: 128
  train_split: 0.9
gpt_config:
  n_layer: 8
  n_head: 8
  n_embd: 512
trainer_config:
  max_epochs: 1
  batch_size: 64
  data_loader_workers: 4
  grad_norm_clip: 1.0
  snapshot_path: gpt_snapshot.pt
  save_every: 4
optimizer_config:
  weight_decay: 0.1
  learning_rate: 0.0003